version: 2
sphinx:
  configuration: doc/conf.py
build:
  os: ubuntu-24.04
  apt_packages:
    - g++
    - libboost-dev
    - libdivide-dev
    - pdf2svg
    - inkscape
  tools:
    python: "3.13"
python:
  install:
    - requirements: requirements-readthedocs.txt
    - method: pip
      path: .
formats:
  - pdf
