#!/bin/bash
set -e -u

function convert()
{
    src="$1"
    trg="$2"
    (echo "# Generated by bootstrap.sh. Do not edit"; cat "$src") > "$trg"
    trollius2asyncio -w -n --no-diffs "$trg"
}

if ! which trollius2asyncio >/dev/null; then
    echo "trollius2asyncio not found. Install trollius-fixers." 1>&2
    exit 1
fi
convert spead2/send/trollius.py spead2/send/asyncio.py
convert spead2/recv/trollius.py spead2/recv/asyncio.py
convert spead2/test/test_send_trollius.py spead2/test/test_send_asyncio.py
# This is a nasty hack, but easier than writing a separate fixer for it.
sed -i 's/spead2\.send\.trollius/spead2.send.asyncio/g' spead2/test/test_send_asyncio.py
autoreconf --install
